### ISSUE TITLE
Missing function definition

### ISSUE THREAD

**Issue by gvdp** [slackapi/deno-slack-hub#19]
Hi,

I'm trying to use these connectors to quickly integrate a Slack app with some apis, however I'm getting the following error:

```
🚫 The provided manifest file does not validate against schema. Consult the additional errors field to locate specific issues (invalid_manifest)

Error Details:

1: Workflow function `knal_input_workflow` step `3` is referring to an unknown function `A04U5QUE5EX#/functions/get_random_gif` (undefined_wf_function_step)
Source: /workflows/knal_input_workflow/steps/3
```

I followed the setup steps in the README, is there another step I still need to do to import this function into my code as well?

Update: this only happens when I try to test the code locally using the cli `slack run` , if I deploy the app it works fine. So presumably I need to make this function known to my local environment somehow?

**Comment by filmaj** [comment]
Are you still seeing this issue @gvdp? Are you `slack run`ning your app in the same workspace as where you `deploy`ed it?
