### ISSUE TITLE
Connector function Google Mail send email body type

### ISSUE THREAD

**Issue by celso-vts** [slackapi/deno-slack-hub#35]
Hi there, 

This is a question about the expected format for `email_body` in the above-mentioned connector.

I'm adding https://api.slack.com/reference/connectors/google.mail/send_email to a workflow on Slack's next-gen platform. The documentation shows `email_body` as a rich_text input. 

The code sample below generates an email body that resembles a stringified JSON output:

```
sampleWorkflow
  .addStep(Connectors.GoogleMail.functions.SendEmail, {
    google_access_token: {
      credential_source: "END_USER",
    },
    recipients: ["john.doe@example.com"],
    subject: "Hi there",
    email_body: "Test",
})
```

The generated email body from Gmail:
```
[{"text":{"text":"Test","type":"mrkdwn","verbatim":false},"type":"section","block_id":"oltZm"}]
```

Surprisingly, if I use the same connector function in Workflow Builder, the `email_body` comes from a rich text form field, the formatting works as expected.

**Comment by filmaj** [comment]
Hey @celso-vts thanks for the report. We are looking it - I am having other troubles with with this step, like getting it to work in WFB 😬 - I have asked the team working on these steps to assist me.

As I get more information I'll post updates here.

**Comment by jesselawson** [comment]
Hi @celso-vts,

Thank you for reporting this. We've reproduced it and can confirm this is a bug on our end. We'll keep this issue open and update it as soon as we know more.

**Comment by jesselawson** [comment]
Hi @celso-vts,

Our teams have tested and shipped a fix for this. I tested it with my own app that uses this connector and can confirm that the email body for the Google SendMail connector now correctly renders as expected. When you get a chance, can you verify on your end? Thanks!

**Comment by celso-vts** [comment]
Hey @jesselawson,

I just tested it out and confirmed it works. 

Thanks for the hard work!
